apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: Patients
    app.kubernetes.io/component: Patients
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: Patients
      app.kubernetes.io/component: Patients
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: Patients
        app.kubernetes.io/component: Patients
    spec:
      containers:
        - name: telegraf
          image: telegraf
          imagePullPolicy: Never ## use local image
          ports:
            - containerPort: 8125
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: Patients
    app.kubernetes.io/component: Patients
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: Patients
      app.kubernetes.io/component: Patients
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: Patients
        app.kubernetes.io/component: Patients
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never ## use local image
          ports:
            - containerPort: 8086
            
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: Patients
    app.kubernetes.io/component: Patients
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: Patients
      app.kubernetes.io/component: Patients
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: Patients
        app.kubernetes.io/component: Patients
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          imagePullPolicy: Never ## use local image
          ports:
            - containerPort: 3000
